// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type AddWatcherRequestBody struct {
	UserID int64 `json:"user_id"`
}

func (o *AddWatcherRequestBody) GetUserID() int64 {
	if o == nil {
		return 0
	}
	return o.UserID
}

type AddWatcherRequest struct {
	Format             components.Format      `pathParam:"style=simple,explode=false,name=format"`
	IssueID            int64                  `pathParam:"style=simple,explode=false,name=issue_id"`
	XRedmineSwitchUser *string                `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
	RequestBody        *AddWatcherRequestBody `request:"mediaType=application/json"`
}

func (o *AddWatcherRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *AddWatcherRequest) GetIssueID() int64 {
	if o == nil {
		return 0
	}
	return o.IssueID
}

func (o *AddWatcherRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

func (o *AddWatcherRequest) GetRequestBody() *AddWatcherRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type AddWatcherResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *AddWatcherResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
