// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type Project struct {
	Name                string                    `json:"name"`
	Identifier          string                    `json:"identifier"`
	Description         *string                   `json:"description,omitempty"`
	Homepage            *string                   `json:"homepage,omitempty"`
	IsPublic            *bool                     `json:"is_public,omitempty"`
	ParentID            *int64                    `json:"parent_id,omitempty"`
	InheritMembers      *bool                     `json:"inherit_members,omitempty"`
	DefaultAssignedToID *int64                    `json:"default_assigned_to_id,omitempty"`
	DefaultVersionID    *int64                    `json:"default_version_id,omitempty"`
	TrackerIds          []int64                   `json:"tracker_ids,omitempty"`
	EnabledModuleNames  []string                  `json:"enabled_module_names,omitempty"`
	IssueCustomFieldIds []int64                   `json:"issue_custom_field_ids,omitempty"`
	CustomFields        []components.CustomFields `json:"custom_fields,omitempty"`
	CustomFieldValues   map[string]any            `json:"custom_field_values,omitempty"`
}

func (o *Project) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Project) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *Project) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Project) GetHomepage() *string {
	if o == nil {
		return nil
	}
	return o.Homepage
}

func (o *Project) GetIsPublic() *bool {
	if o == nil {
		return nil
	}
	return o.IsPublic
}

func (o *Project) GetParentID() *int64 {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *Project) GetInheritMembers() *bool {
	if o == nil {
		return nil
	}
	return o.InheritMembers
}

func (o *Project) GetDefaultAssignedToID() *int64 {
	if o == nil {
		return nil
	}
	return o.DefaultAssignedToID
}

func (o *Project) GetDefaultVersionID() *int64 {
	if o == nil {
		return nil
	}
	return o.DefaultVersionID
}

func (o *Project) GetTrackerIds() []int64 {
	if o == nil {
		return nil
	}
	return o.TrackerIds
}

func (o *Project) GetEnabledModuleNames() []string {
	if o == nil {
		return nil
	}
	return o.EnabledModuleNames
}

func (o *Project) GetIssueCustomFieldIds() []int64 {
	if o == nil {
		return nil
	}
	return o.IssueCustomFieldIds
}

func (o *Project) GetCustomFields() []components.CustomFields {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *Project) GetCustomFieldValues() map[string]any {
	if o == nil {
		return nil
	}
	return o.CustomFieldValues
}

type CreateProjectRequestBody struct {
	Project Project `json:"project"`
}

func (o *CreateProjectRequestBody) GetProject() Project {
	if o == nil {
		return Project{}
	}
	return o.Project
}

type CreateProjectRequest struct {
	Format             components.Format         `pathParam:"style=simple,explode=false,name=format"`
	XRedmineSwitchUser *string                   `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
	RequestBody        *CreateProjectRequestBody `request:"mediaType=application/json"`
}

func (o *CreateProjectRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *CreateProjectRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

func (o *CreateProjectRequest) GetRequestBody() *CreateProjectRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type CreateProjectResponseBody struct {
	Project components.Project `json:"project"`
}

func (o *CreateProjectResponseBody) GetProject() components.Project {
	if o == nil {
		return components.Project{}
	}
	return o.Project
}

type CreateProjectResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *CreateProjectResponseBody
}

func (o *CreateProjectResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateProjectResponse) GetObject() *CreateProjectResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
