// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type Group struct {
	Name              *string                   `json:"name,omitempty"`
	UserIds           []int64                   `json:"user_ids,omitempty"`
	CustomFields      []components.CustomFields `json:"custom_fields,omitempty"`
	CustomFieldValues map[string]any            `json:"custom_field_values,omitempty"`
}

func (o *Group) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Group) GetUserIds() []int64 {
	if o == nil {
		return nil
	}
	return o.UserIds
}

func (o *Group) GetCustomFields() []components.CustomFields {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *Group) GetCustomFieldValues() map[string]any {
	if o == nil {
		return nil
	}
	return o.CustomFieldValues
}

type CreateGroupRequestBody struct {
	Group Group `json:"group"`
}

func (o *CreateGroupRequestBody) GetGroup() Group {
	if o == nil {
		return Group{}
	}
	return o.Group
}

type CreateGroupRequest struct {
	Format             components.Format       `pathParam:"style=simple,explode=false,name=format"`
	XRedmineSwitchUser *string                 `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
	RequestBody        *CreateGroupRequestBody `request:"mediaType=application/json"`
}

func (o *CreateGroupRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *CreateGroupRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

func (o *CreateGroupRequest) GetRequestBody() *CreateGroupRequestBody {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

type CreateGroupResponseBody struct {
	Group *components.GroupSimple `json:"group,omitempty"`
}

func (o *CreateGroupResponseBody) GetGroup() *components.GroupSimple {
	if o == nil {
		return nil
	}
	return o.Group
}

type CreateGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *CreateGroupResponseBody
}

func (o *CreateGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateGroupResponse) GetObject() *CreateGroupResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
