// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type DeleteNewsRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	NewsID             int64             `pathParam:"style=simple,explode=false,name=news_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DeleteNewsRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *DeleteNewsRequest) GetNewsID() int64 {
	if o == nil {
		return 0
	}
	return o.NewsID
}

func (o *DeleteNewsRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DeleteNewsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteNewsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
