// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type DeleteTimeEntryRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	TimeEntryID        int64             `pathParam:"style=simple,explode=false,name=time_entry_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DeleteTimeEntryRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *DeleteTimeEntryRequest) GetTimeEntryID() int64 {
	if o == nil {
		return 0
	}
	return o.TimeEntryID
}

func (o *DeleteTimeEntryRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DeleteTimeEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteTimeEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
