// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type DeleteMembershipRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	MembershipID       int64             `pathParam:"style=simple,explode=false,name=membership_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DeleteMembershipRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *DeleteMembershipRequest) GetMembershipID() int64 {
	if o == nil {
		return 0
	}
	return o.MembershipID
}

func (o *DeleteMembershipRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DeleteMembershipResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteMembershipResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
