// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type DeleteUserRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	UserID             int64             `pathParam:"style=simple,explode=false,name=user_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DeleteUserRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *DeleteUserRequest) GetUserID() int64 {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *DeleteUserRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DeleteUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
