// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type DeleteAttachmentRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	AttachmentID       float64           `pathParam:"style=simple,explode=false,name=attachment_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DeleteAttachmentRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *DeleteAttachmentRequest) GetAttachmentID() float64 {
	if o == nil {
		return 0.0
	}
	return o.AttachmentID
}

func (o *DeleteAttachmentRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DeleteAttachmentResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *DeleteAttachmentResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
