// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"io"

	"github.com/dmji/go-redmine/models/components"
)

type DownloadAttachmentFileRequest struct {
	AttachmentID       float64 `pathParam:"style=simple,explode=false,name=attachment_id"`
	Filename           string  `pathParam:"style=simple,explode=false,name=filename"`
	XRedmineSwitchUser *string `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *DownloadAttachmentFileRequest) GetAttachmentID() float64 {
	if o == nil {
		return 0.0
	}
	return o.AttachmentID
}

func (o *DownloadAttachmentFileRequest) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *DownloadAttachmentFileRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type DownloadAttachmentFileResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// The Close method must be called on this field, even if it is not used, to prevent resource leaks.
	ResponseStream io.ReadCloser
}

func (o *DownloadAttachmentFileResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *DownloadAttachmentFileResponse) GetResponseStream() io.ReadCloser {
	if o == nil {
		return nil
	}
	return o.ResponseStream
}
