// Code generated by Speakeasy (https://speakeasy.com).

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type GetDocumentCategoriesRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *GetDocumentCategoriesRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *GetDocumentCategoriesRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type GetDocumentCategoriesResponseBody struct {
	DocumentCategories []components.DocumentCategory `json:"document_categories"`
}

func (o *GetDocumentCategoriesResponseBody) GetDocumentCategories() []components.DocumentCategory {
	if o == nil {
		return []components.DocumentCategory{}
	}
	return o.DocumentCategories
}

type GetDocumentCategoriesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetDocumentCategoriesResponseBody
}

func (o *GetDocumentCategoriesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetDocumentCategoriesResponse) GetObject() *GetDocumentCategoriesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
