// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type GetMembershipsRequest struct {
	Format             components.Format          `pathParam:"style=simple,explode=false,name=format"`
	ProjectID          int64                      `pathParam:"style=simple,explode=false,name=project_id"`
	Offset             *int64                     `queryParam:"style=form,explode=true,name=offset"`
	Limit              *int64                     `queryParam:"style=form,explode=true,name=limit"`
	Nometa             *components.Nometa         `queryParam:"style=form,explode=true,name=nometa"`
	XRedmineSwitchUser *string                    `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
	XRedmineNometa     *components.XRedmineNometa `header:"style=simple,explode=false,name=X-Redmine-Nometa"`
}

func (o *GetMembershipsRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *GetMembershipsRequest) GetProjectID() int64 {
	if o == nil {
		return 0
	}
	return o.ProjectID
}

func (o *GetMembershipsRequest) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetMembershipsRequest) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetMembershipsRequest) GetNometa() *components.Nometa {
	if o == nil {
		return nil
	}
	return o.Nometa
}

func (o *GetMembershipsRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

func (o *GetMembershipsRequest) GetXRedmineNometa() *components.XRedmineNometa {
	if o == nil {
		return nil
	}
	return o.XRedmineNometa
}

type GetMembershipsResponseBody struct {
	Memberships []components.Membership `json:"memberships"`
	TotalCount  *int64                  `json:"total_count,omitempty"`
	Offset      *int64                  `json:"offset,omitempty"`
	Limit       *int64                  `json:"limit,omitempty"`
}

func (o *GetMembershipsResponseBody) GetMemberships() []components.Membership {
	if o == nil {
		return []components.Membership{}
	}
	return o.Memberships
}

func (o *GetMembershipsResponseBody) GetTotalCount() *int64 {
	if o == nil {
		return nil
	}
	return o.TotalCount
}

func (o *GetMembershipsResponseBody) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetMembershipsResponseBody) GetLimit() *int64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

type GetMembershipsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetMembershipsResponseBody
}

func (o *GetMembershipsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetMembershipsResponse) GetObject() *GetMembershipsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
