// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type GetRolesRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *GetRolesRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *GetRolesRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type GetRolesResponseBody struct {
	Roles []components.IDName `json:"roles"`
}

func (o *GetRolesResponseBody) GetRoles() []components.IDName {
	if o == nil {
		return []components.IDName{}
	}
	return o.Roles
}

type GetRolesResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetRolesResponseBody
}

func (o *GetRolesResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetRolesResponse) GetObject() *GetRolesResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
