// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type GetTimeEntryRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	TimeEntryID        int64             `pathParam:"style=simple,explode=false,name=time_entry_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *GetTimeEntryRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *GetTimeEntryRequest) GetTimeEntryID() int64 {
	if o == nil {
		return 0
	}
	return o.TimeEntryID
}

func (o *GetTimeEntryRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type GetTimeEntryResponseBody struct {
	TimeEntry components.TimeEntry `json:"time_entry"`
}

func (o *GetTimeEntryResponseBody) GetTimeEntry() components.TimeEntry {
	if o == nil {
		return components.TimeEntry{}
	}
	return o.TimeEntry
}

type GetTimeEntryResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	Object   *GetTimeEntryResponseBody
}

func (o *GetTimeEntryResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *GetTimeEntryResponse) GetObject() *GetTimeEntryResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
