// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/dmji/go-redmine/models/components"
)

type RemoveUserFromGroupRequest struct {
	Format             components.Format `pathParam:"style=simple,explode=false,name=format"`
	GroupID            int64             `pathParam:"style=simple,explode=false,name=group_id"`
	UserID             int64             `pathParam:"style=simple,explode=false,name=user_id"`
	XRedmineSwitchUser *string           `header:"style=simple,explode=false,name=X-Redmine-Switch-User"`
}

func (o *RemoveUserFromGroupRequest) GetFormat() components.Format {
	if o == nil {
		return components.Format("")
	}
	return o.Format
}

func (o *RemoveUserFromGroupRequest) GetGroupID() int64 {
	if o == nil {
		return 0
	}
	return o.GroupID
}

func (o *RemoveUserFromGroupRequest) GetUserID() int64 {
	if o == nil {
		return 0
	}
	return o.UserID
}

func (o *RemoveUserFromGroupRequest) GetXRedmineSwitchUser() *string {
	if o == nil {
		return nil
	}
	return o.XRedmineSwitchUser
}

type RemoveUserFromGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (o *RemoveUserFromGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}
