// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Attachment struct {
	ID           int64   `json:"id"`
	Filename     string  `json:"filename"`
	Filesize     int64   `json:"filesize"`
	ContentType  string  `json:"content_type"`
	Description  string  `json:"description"`
	ContentURL   string  `json:"content_url"`
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	Author       IDName  `json:"author"`
	CreatedOn    string  `json:"created_on"`
}

func (o *Attachment) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Attachment) GetFilename() string {
	if o == nil {
		return ""
	}
	return o.Filename
}

func (o *Attachment) GetFilesize() int64 {
	if o == nil {
		return 0
	}
	return o.Filesize
}

func (o *Attachment) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *Attachment) GetDescription() string {
	if o == nil {
		return ""
	}
	return o.Description
}

func (o *Attachment) GetContentURL() string {
	if o == nil {
		return ""
	}
	return o.ContentURL
}

func (o *Attachment) GetThumbnailURL() *string {
	if o == nil {
		return nil
	}
	return o.ThumbnailURL
}

func (o *Attachment) GetAuthor() IDName {
	if o == nil {
		return IDName{}
	}
	return o.Author
}

func (o *Attachment) GetCreatedOn() string {
	if o == nil {
		return ""
	}
	return o.CreatedOn
}
