// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GroupSimple struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
}

func (o *GroupSimple) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *GroupSimple) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *GroupSimple) GetCustomFields() []CustomFieldValue {
	if o == nil {
		return nil
	}
	return o.CustomFields
}
