// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type GroupMemberships struct {
	ID      int64    `json:"id"`
	Project IDName   `json:"project"`
	Roles   []IDName `json:"roles"`
}

func (o *GroupMemberships) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *GroupMemberships) GetProject() IDName {
	if o == nil {
		return IDName{}
	}
	return o.Project
}

func (o *GroupMemberships) GetRoles() []IDName {
	if o == nil {
		return []IDName{}
	}
	return o.Roles
}

type Group struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	CustomFields []CustomFieldValue `json:"custom_fields,omitempty"`
	Users        []IDName           `json:"users,omitempty"`
	Memberships  []GroupMemberships `json:"memberships,omitempty"`
}

func (o *Group) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Group) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Group) GetCustomFields() []CustomFieldValue {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *Group) GetUsers() []IDName {
	if o == nil {
		return nil
	}
	return o.Users
}

func (o *Group) GetMemberships() []GroupMemberships {
	if o == nil {
		return nil
	}
	return o.Memberships
}
