// Code generated by Speakeasy (https://speakeasy.com).

package components

type IDName struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (o *IDName) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *IDName) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}
