// Code generated by Speakeasy (https://speakeasy.com).

package components

type IssueCategory struct {
	ID         int64   `json:"id"`
	Project    IDName  `json:"project"`
	Name       string  `json:"name"`
	AssignedTo *IDName `json:"assigned_to,omitempty"`
}

func (o *IssueCategory) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *IssueCategory) GetProject() IDName {
	if o == nil {
		return IDName{}
	}
	return o.Project
}

func (o *IssueCategory) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *IssueCategory) GetAssignedTo() *IDName {
	if o == nil {
		return nil
	}
	return o.AssignedTo
}
