// Code generated by Speakeasy (https://speakeasy.com).

package components

type IssueRelation struct {
	ID           int64  `json:"id"`
	IssueID      int64  `json:"issue_id"`
	IssueToID    int64  `json:"issue_to_id"`
	RelationType string `json:"relation_type"`
	Delay        *int64 `json:"delay"`
}

func (o *IssueRelation) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *IssueRelation) GetIssueID() int64 {
	if o == nil {
		return 0
	}
	return o.IssueID
}

func (o *IssueRelation) GetIssueToID() int64 {
	if o == nil {
		return 0
	}
	return o.IssueToID
}

func (o *IssueRelation) GetRelationType() string {
	if o == nil {
		return ""
	}
	return o.RelationType
}

func (o *IssueRelation) GetDelay() *int64 {
	if o == nil {
		return nil
	}
	return o.Delay
}
