// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Membership struct {
	ID      int64    `json:"id"`
	Project IDName   `json:"project"`
	User    *IDName  `json:"user,omitempty"`
	Group   *IDName  `json:"group,omitempty"`
	Roles   []IDName `json:"roles"`
}

func (o *Membership) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Membership) GetProject() IDName {
	if o == nil {
		return IDName{}
	}
	return o.Project
}

func (o *Membership) GetUser() *IDName {
	if o == nil {
		return nil
	}
	return o.User
}

func (o *Membership) GetGroup() *IDName {
	if o == nil {
		return nil
	}
	return o.Group
}

func (o *Membership) GetRoles() []IDName {
	if o == nil {
		return []IDName{}
	}
	return o.Roles
}
