// Code generated by Speakeasy (https://speakeasy.com).

package components

type NewsComment struct {
	ID      int64  `json:"id"`
	Author  IDName `json:"author"`
	Content string `json:"content"`
}

func (o *NewsComment) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *NewsComment) GetAuthor() IDName {
	if o == nil {
		return IDName{}
	}
	return o.Author
}

func (o *NewsComment) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}
