// Code generated by Speakeasy (https://speakeasy.com).

package components

import (
	"time"

	"github.com/dmji/go-redmine/internal/utils"
)

type ProjectSimple struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Identifier          string             `json:"identifier"`
	Description         *string            `json:"description"`
	Parent              *IDName            `json:"parent,omitempty"`
	Status              int64              `json:"status"`
	IsPublic            bool               `json:"is_public"`
	InheritMembers      bool               `json:"inherit_members"`
	CustomFields        []CustomFieldValue `json:"custom_fields,omitempty"`
	Trackers            []IDName           `json:"trackers,omitempty"`
	IssueCategories     []IDName           `json:"issue_categories,omitempty"`
	TimeEntryActivities []IDName           `json:"time_entry_activities,omitempty"`
	EnabledModules      []IDName           `json:"enabled_modules,omitempty"`
	IssueCustomFields   []IDName           `json:"issue_custom_fields,omitempty"`
	CreatedOn           time.Time          `json:"created_on"`
	UpdatedOn           time.Time          `json:"updated_on"`
}

func (p ProjectSimple) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *ProjectSimple) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ProjectSimple) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *ProjectSimple) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ProjectSimple) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *ProjectSimple) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *ProjectSimple) GetParent() *IDName {
	if o == nil {
		return nil
	}
	return o.Parent
}

func (o *ProjectSimple) GetStatus() int64 {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *ProjectSimple) GetIsPublic() bool {
	if o == nil {
		return false
	}
	return o.IsPublic
}

func (o *ProjectSimple) GetInheritMembers() bool {
	if o == nil {
		return false
	}
	return o.InheritMembers
}

func (o *ProjectSimple) GetCustomFields() []CustomFieldValue {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *ProjectSimple) GetTrackers() []IDName {
	if o == nil {
		return nil
	}
	return o.Trackers
}

func (o *ProjectSimple) GetIssueCategories() []IDName {
	if o == nil {
		return nil
	}
	return o.IssueCategories
}

func (o *ProjectSimple) GetTimeEntryActivities() []IDName {
	if o == nil {
		return nil
	}
	return o.TimeEntryActivities
}

func (o *ProjectSimple) GetEnabledModules() []IDName {
	if o == nil {
		return nil
	}
	return o.EnabledModules
}

func (o *ProjectSimple) GetIssueCustomFields() []IDName {
	if o == nil {
		return nil
	}
	return o.IssueCustomFields
}

func (o *ProjectSimple) GetCreatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedOn
}

func (o *ProjectSimple) GetUpdatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedOn
}
