// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"github.com/dmji/go-redmine/internal/utils"
	"time"
)

type Project struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	Identifier          string             `json:"identifier"`
	Description         *string            `json:"description"`
	Homepage            *string            `json:"homepage,omitempty"`
	Parent              *IDName            `json:"parent,omitempty"`
	Status              int64              `json:"status"`
	IsPublic            bool               `json:"is_public"`
	InheritMembers      bool               `json:"inherit_members"`
	DefaultVersion      *IDName            `json:"default_version,omitempty"`
	DefaultAssignee     *IDName            `json:"default_assignee,omitempty"`
	CustomFields        []CustomFieldValue `json:"custom_fields,omitempty"`
	Trackers            []IDName           `json:"trackers,omitempty"`
	IssueCategories     []IDName           `json:"issue_categories,omitempty"`
	TimeEntryActivities []IDName           `json:"time_entry_activities,omitempty"`
	EnabledModules      []IDName           `json:"enabled_modules,omitempty"`
	IssueCustomFields   []IDName           `json:"issue_custom_fields,omitempty"`
	CreatedOn           time.Time          `json:"created_on"`
	UpdatedOn           time.Time          `json:"updated_on"`
}

func (p Project) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Project) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *Project) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *Project) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *Project) GetIdentifier() string {
	if o == nil {
		return ""
	}
	return o.Identifier
}

func (o *Project) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Project) GetHomepage() *string {
	if o == nil {
		return nil
	}
	return o.Homepage
}

func (o *Project) GetParent() *IDName {
	if o == nil {
		return nil
	}
	return o.Parent
}

func (o *Project) GetStatus() int64 {
	if o == nil {
		return 0
	}
	return o.Status
}

func (o *Project) GetIsPublic() bool {
	if o == nil {
		return false
	}
	return o.IsPublic
}

func (o *Project) GetInheritMembers() bool {
	if o == nil {
		return false
	}
	return o.InheritMembers
}

func (o *Project) GetDefaultVersion() *IDName {
	if o == nil {
		return nil
	}
	return o.DefaultVersion
}

func (o *Project) GetDefaultAssignee() *IDName {
	if o == nil {
		return nil
	}
	return o.DefaultAssignee
}

func (o *Project) GetCustomFields() []CustomFieldValue {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *Project) GetTrackers() []IDName {
	if o == nil {
		return nil
	}
	return o.Trackers
}

func (o *Project) GetIssueCategories() []IDName {
	if o == nil {
		return nil
	}
	return o.IssueCategories
}

func (o *Project) GetTimeEntryActivities() []IDName {
	if o == nil {
		return nil
	}
	return o.TimeEntryActivities
}

func (o *Project) GetEnabledModules() []IDName {
	if o == nil {
		return nil
	}
	return o.EnabledModules
}

func (o *Project) GetIssueCustomFields() []IDName {
	if o == nil {
		return nil
	}
	return o.IssueCustomFields
}

func (o *Project) GetCreatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedOn
}

func (o *Project) GetUpdatedOn() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedOn
}
