// Code generated by Speakeasy (https://speakeasy.com).

package components

type Tracker struct {
	ID                    *int64   `json:"id,omitempty"`
	Name                  *string  `json:"name,omitempty"`
	DefaultStatus         *IDName  `json:"default_status,omitempty"`
	Description           *string  `json:"description,omitempty"`
	EnabledStandardFields []string `json:"enabled_standard_fields,omitempty"`
}

func (o *Tracker) GetID() *int64 {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *Tracker) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *Tracker) GetDefaultStatus() *IDName {
	if o == nil {
		return nil
	}
	return o.DefaultStatus
}

func (o *Tracker) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Tracker) GetEnabledStandardFields() []string {
	if o == nil {
		return nil
	}
	return o.EnabledStandardFields
}
