// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

type Uploads struct {
	Token       *string `json:"token,omitempty"`
	Filename    *string `json:"filename,omitempty"`
	Description *string `json:"description,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
}

func (o *Uploads) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

func (o *Uploads) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}

func (o *Uploads) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Uploads) GetContentType() *string {
	if o == nil {
		return nil
	}
	return o.ContentType
}
