// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"
)

// Date is a wrapper around time.Time that allows for JSON marshaling a date string formatted as "2006-01-02".
type Date struct {
	time.Time
}

var (
	_ json.Marshaler   = &Date{}
	_ json.Unmarshaler = &Date{}
	_ fmt.Stringer     = &Date{}
)

// DateFromString returns a Date from a string formatted as "2006-01-02".
func DateFromString(str string) (Date, error) {
	var d Date
	var err error

	d.Time, err = time.Parse("2006-01-02", str)
	return d, err
}

func (d Date) GetTime() time.Time {
	return d.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf(`"%s"`, d.Time.Format("2006-01-02"))), nil
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var err error

	str := string(data)
	str = strings.Trim(str, `"`)

	d.Time, err = time.Parse("2006-01-02", str)
	return err
}

func (d Date) String() string {
	return d.Time.Format("2006-01-02")
}
