// Code generated by Speakeasy (https://speakeasy.com).

package apierrors

import (
	"encoding/json"
)

type Errors struct {
	Errors []string `json:"errors"`
}

var _ error = &Errors{}

func (e *Errors) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
