workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Redmine API:
        inputs:
            - location: ..\redmine-openapi.yaml
        overlays:
            - location: .speakeasy\speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/dmji/jikan/redmine-api
targets:
    go-redmine:
        target: go
        source: Redmine API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/dmji/jikan/redmine-api-go-code-samples
            labelOverride:
                fixedValue: Go (SDK)
            blocking: false
